### ISSUE TITLE
Update to v0.7.0 - Cannot resolve module/Cannot find module

### ISSUE THREAD

**Issue by daschi** [ericgio/react-bootstrap-typeahead#42]
Thanks for this project! I am trying to update to the new version and noticed an issue.

After updating to 0.7.0, my project isn't able to resolve the module. I tried to change `main` from `lib/index.js` to `dist/react-bootstrap-typeahead.js` in `package.json` and I was able to build with `npm build`, but I am still seeing this error in the browser console: 

`Uncaught Error: Cannot find module "react-bootstrap-typeahead"`

**Comment by ericgio** [comment]
Hi, sorry you're having problems. Can you please provide explicit repro steps? What kind of environment are you working in? You shouldn't need to change `package.json` to use the module.

**Comment by magmel48** [comment]
@ericgio There is no lib/index.js (it specified in main section of package) after `npm install`. Please check

**Comment by ericgio** [comment]
Ah crap, I think I found the problem. Not sure why the publish step didn't abort.

**Comment by ericgio** [comment]
Just published 0.7.1 which should fix the problem. It was a syntax issue that oddly did not cause the build to fail, but caused it to execute improperly so that not all the files were generated. Sigh. Thanks for your patience and for reporting the issue.
